#!/usr/bin/env python3
"""Generate ps5_localized_strings.inc from rpcs3qt/localized_emu.h (the Qt frontend's English text).

Each `case localized_string_id::ID: return tr("text"[, "context"])...;` becomes `{ID, "text"}`.
Qt's %0..%9 placeholders are kept; the frontend substitutes the argument it is given.
"""
import re
import sys

src, out = sys.argv[1], sys.argv[2]
text = open(src, encoding='utf-8').read()
case = re.compile(r'case\s+localized_string_id::(\w+)\s*:\s*return\s+(?:tr\(\s*((?:"(?:[^"\\]|\\.)*"\s*)+)|"((?:[^"\\]|\\.)*)")')
seen = set()
lines = []
for m in case.finditer(text):
    ident = m.group(1)
    if ident in seen:
        continue
    seen.add(ident)
    if m.group(2) is not None:
        # Concatenated literals: "a" "b" -> "a" "b" (C++ joins them); drop the tr context argument
        literal = m.group(2).strip()
    else:
        literal = '"' + m.group(3) + '"'
    lines.append(f'\t{{ localized_string_id::{ident}, {literal} }},')
open(out, 'w', encoding='utf-8').write('// Generated by ps5/tools/gen_localized.py from rpcs3qt/localized_emu.h: do not edit\n' + '\n'.join(lines) + '\n')
print(f'{len(lines)} strings')
